//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace QueueServices
{
    using System.Xml.Serialization;
    using System.Runtime.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.17929.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://EventConsumerProj.FireEvent")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://EventConsumerProj.FireEvent", IsNullable = false)]
    [DataContract(Name = "FireEvent", Namespace = "http://EventConsumerProj.FireEvent")]
    public partial class FireEvent
    {
        [DataMember(Name="AlertType")]
        private string alertTypeField;
        [DataMember(Name = "AlertColor")]
        private string alertColorField;
        [DataMember(Name = "Temperature")]
        private int temperatureField;
        [DataMember(Name = "AlertMessage")]
        private string alertMessageField;
        [DataMember(Name = "ZipCode")]
        private string zipCodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AlertType
        {
            get
            {
                return this.alertTypeField;
            }
            set
            {
                this.alertTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AlertColor
        {
            get
            {
                return this.alertColorField;
            }
            set
            {
                this.alertColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Temperature
        {
            get
            {
                return this.temperatureField;
            }
            set
            {
                this.temperatureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AlertMessage
        {
            get
            {
                return this.alertMessageField;
            }
            set
            {
                this.alertMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }
    }
}
