//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueServices
{
    using System.Xml.Serialization;
    using System.Runtime.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.17929.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://WeatherBizTalkService.WeatherEvent")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://WeatherBizTalkService.WeatherEvent", IsNullable = false)]
    [DataContract(Name = "WeatherEvent", Namespace = "http://WeatherBizTalkService.WeatherEvent")]
    public partial class WeatherEvent
    {
        [DataMember(Name = "EventType")]
        private string eventTypeField;
        [DataMember(Name = "Temperature")]
        private int temperatureField;
        [DataMember(Name = "IsAlert")]
        private bool isAlertField;
        [DataMember(Name = "AffectedArea")]
        private string affectedAreaField;
        [DataMember(Name = "ZipCode")]
        private string zipCodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EventType
        {
            get
            {
                return this.eventTypeField;
            }
            set
            {
                this.eventTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Temperature
        {
            get
            {
                return this.temperatureField;
            }
            set
            {
                this.temperatureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IsAlert
        {
            get
            {
                return this.isAlertField;
            }
            set
            {
                this.isAlertField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AffectedArea
        {
            get
            {
                return this.affectedAreaField;
            }
            set
            {
                this.affectedAreaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }
    }
}
